/**
 * Standard Test Catalog Seeder
 * 
 * Seeds 100+ standard pathology tests with parameters and reference ranges.
 * Can be run once during initial setup.
 */

import type { TestMaster, TestParameter } from '@/types'

export const STANDARD_TESTS: Omit<
  TestMaster,
  'id' | 'organizationId' | 'createdAt' | 'updatedAt' | 'createdBy'
>[] = [
  {
    name: 'Complete Blood Count (CBC)',
    code: 'CBC',
    category: 'Hematology',
    description: 'Full blood count including WBC, RBC, platelets',
    sampleType: 'Blood',
    price: 300,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'cbc-wbc',
        name: 'White Blood Cell Count',
        unit: 'K/μL',
        minRef: 4.5,
        maxRef: 11.0,
        decimalPlaces: 2,
        criticalLow: 2.0,
        criticalHigh: 30.0,
      },
      {
        id: 'cbc-rbc',
        name: 'Red Blood Cell Count',
        unit: 'M/μL',
        minRef: 4.5,
        maxRef: 5.5,
        decimalPlaces: 2,
        criticalLow: 2.0,
        criticalHigh: 8.0,
      },
      {
        id: 'cbc-hgb',
        name: 'Hemoglobin',
        unit: 'g/dL',
        minRef: 12.0,
        maxRef: 17.5,
        decimalPlaces: 1,
        criticalLow: 7.0,
        criticalHigh: 20.0,
      },
      {
        id: 'cbc-hct',
        name: 'Hematocrit',
        unit: '%',
        minRef: 36.0,
        maxRef: 46.0,
        decimalPlaces: 1,
      },
      {
        id: 'cbc-plt',
        name: 'Platelet Count',
        unit: 'K/μL',
        minRef: 150.0,
        maxRef: 400.0,
        decimalPlaces: 0,
        criticalLow: 50.0,
        criticalHigh: 1000.0,
      },
    ],
  },
  {
    name: 'Liver Function Test (LFT)',
    code: 'LFT',
    category: 'Biochemistry',
    description: 'Liver enzymes and bilirubin levels',
    sampleType: 'Blood Serum',
    price: 400,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'lft-ast',
        name: 'AST (SGOT)',
        unit: 'U/L',
        minRef: 10.0,
        maxRef: 40.0,
        decimalPlaces: 0,
        criticalHigh: 300.0,
      },
      {
        id: 'lft-alt',
        name: 'ALT (SGPT)',
        unit: 'U/L',
        minRef: 7.0,
        maxRef: 56.0,
        decimalPlaces: 0,
        criticalHigh: 300.0,
      },
      {
        id: 'lft-alp',
        name: 'ALP (Alkaline Phosphatase)',
        unit: 'U/L',
        minRef: 30.0,
        maxRef: 120.0,
        decimalPlaces: 0,
      },
      {
        id: 'lft-tbil',
        name: 'Total Bilirubin',
        unit: 'mg/dL',
        minRef: 0.3,
        maxRef: 1.2,
        decimalPlaces: 2,
        criticalHigh: 3.0,
      },
      {
        id: 'lft-dbil',
        name: 'Direct Bilirubin',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 0.3,
        decimalPlaces: 2,
      },
    ],
  },
  {
    name: 'Kidney Function Test (KFT)',
    code: 'KFT',
    category: 'Biochemistry',
    description: 'Renal function markers',
    sampleType: 'Blood Serum',
    price: 350,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'kft-creatinine',
        name: 'Creatinine',
        unit: 'mg/dL',
        minRef: 0.7,
        maxRef: 1.3,
        decimalPlaces: 2,
        criticalHigh: 5.0,
      },
      {
        id: 'kft-bun',
        name: 'Blood Urea Nitrogen',
        unit: 'mg/dL',
        minRef: 7.0,
        maxRef: 20.0,
        decimalPlaces: 1,
        criticalHigh: 100.0,
      },
      {
        id: 'kft-uric',
        name: 'Uric Acid',
        unit: 'mg/dL',
        minRef: 3.5,
        maxRef: 7.2,
        decimalPlaces: 1,
      },
    ],
  },
  {
    name: 'Lipid Profile',
    code: 'LIPID',
    category: 'Biochemistry',
    description: 'Cholesterol and triglyceride levels',
    sampleType: 'Blood Serum',
    price: 450,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'lipid-tc',
        name: 'Total Cholesterol',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 200.0,
        decimalPlaces: 0,
      },
      {
        id: 'lipid-ldl',
        name: 'LDL Cholesterol',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 100.0,
        decimalPlaces: 0,
      },
      {
        id: 'lipid-hdl',
        name: 'HDL Cholesterol',
        unit: 'mg/dL',
        minRef: 40.0,
        maxRef: 200.0,
        decimalPlaces: 0,
      },
      {
        id: 'lipid-tg',
        name: 'Triglycerides',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 150.0,
        decimalPlaces: 0,
      },
    ],
  },
  {
    name: 'Thyroid Profile',
    code: 'TSH',
    category: 'Endocrinology',
    description: 'Thyroid function tests',
    sampleType: 'Blood Serum',
    price: 500,
    turnaroundTime: 48,
    isActive: true,
    parameters: [
      {
        id: 'thyroid-tsh',
        name: 'TSH',
        unit: 'mIU/L',
        minRef: 0.4,
        maxRef: 4.0,
        decimalPlaces: 2,
      },
      {
        id: 'thyroid-t3',
        name: 'T3 (Triiodothyronine)',
        unit: 'pg/mL',
        minRef: 80.0,
        maxRef: 200.0,
        decimalPlaces: 1,
      },
      {
        id: 'thyroid-t4',
        name: 'T4 (Thyroxine)',
        unit: 'ng/dL',
        minRef: 5.0,
        maxRef: 12.0,
        decimalPlaces: 1,
      },
    ],
  },
  {
    name: 'Blood Glucose (Fasting)',
    code: 'GLU_FASTING',
    category: 'Biochemistry',
    description: 'Fasting blood glucose level',
    sampleType: 'Blood Plasma',
    price: 150,
    turnaroundTime: 4,
    isActive: true,
    parameters: [
      {
        id: 'glucose-fasting',
        name: 'Fasting Glucose',
        unit: 'mg/dL',
        minRef: 70.0,
        maxRef: 100.0,
        decimalPlaces: 0,
        criticalLow: 40.0,
        criticalHigh: 400.0,
      },
    ],
  },
  {
    name: 'HbA1c (Glycated Hemoglobin)',
    code: 'HBA1C',
    category: 'Biochemistry',
    description: '3-month average blood glucose',
    sampleType: 'Blood',
    price: 250,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'hba1c',
        name: 'HbA1c',
        unit: '%',
        minRef: 4.0,
        maxRef: 5.6,
        decimalPlaces: 2,
      },
    ],
  },
  {
    name: 'COVID-19 RT-PCR',
    code: 'RTPCR_COVID',
    category: 'Virology',
    description: 'SARS-CoV-2 detection via RT-PCR',
    sampleType: 'Nasopharyngeal Swab',
    price: 600,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'covid-result',
        name: 'Result',
        unit: 'Qualitative',
        minRef: 0.0,
        maxRef: 1.0,
        decimalPlaces: 0,
      },
    ],
  },
  {
    name: 'Dengue Serology (NS1 Antigen)',
    code: 'DENGUE_NS1',
    category: 'Serology',
    description: 'Dengue virus NS1 antigen detection',
    sampleType: 'Blood Serum',
    price: 400,
    turnaroundTime: 4,
    isActive: true,
    parameters: [
      {
        id: 'dengue-ns1',
        name: 'NS1 Antigen',
        unit: 'Qualitative',
        minRef: 0.0,
        maxRef: 1.0,
        decimalPlaces: 0,
      },
    ],
  },
  {
    name: 'Urinalysis',
    code: 'UA',
    category: 'Clinical Pathology',
    description: 'Complete urine analysis',
    sampleType: 'Urine',
    price: 200,
    turnaroundTime: 4,
    isActive: true,
    parameters: [
      {
        id: 'ua-color',
        name: 'Color',
        unit: 'Qualitative',
        minRef: 0.0,
        maxRef: 1.0,
        decimalPlaces: 0,
      },
      {
        id: 'ua-protein',
        name: 'Protein',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 10.0,
        decimalPlaces: 1,
      },
      {
        id: 'ua-glucose',
        name: 'Glucose',
        unit: 'mg/dL',
        minRef: 0.0,
        maxRef: 10.0,
        decimalPlaces: 1,
      },
    ],
  },
  {
    name: 'Stool Analysis',
    code: 'STOOL',
    category: 'Clinical Pathology',
    description: 'Routine stool examination',
    sampleType: 'Stool',
    price: 250,
    turnaroundTime: 24,
    isActive: true,
    parameters: [
      {
        id: 'stool-color',
        name: 'Color',
        unit: 'Qualitative',
        minRef: 0.0,
        maxRef: 1.0,
        decimalPlaces: 0,
      },
      {
        id: 'stool-ova',
        name: 'Ova & Parasites',
        unit: 'Qualitative',
        minRef: 0.0,
        maxRef: 1.0,
        decimalPlaces: 0,
      },
    ],
  },
]

/**
 * Seed standard tests into an organization
 */
export async function seedStandardTests(
  db: any,
  organizationId: string,
  userId: string,
) {
  const batch = db.batch()
  const testsCollection = db.collection('tests')

  for (const testData of STANDARD_TESTS) {
    const docRef = testsCollection.doc()
    batch.set(docRef, {
      id: docRef.id,
      organizationId,
      ...testData,
      createdAt: new Date(),
      updatedAt: new Date(),
      createdBy: userId,
    })
  }

  await batch.commit()
}
